application: eloquent-geek
version: 0-1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /post
  script: _go_app

- url: /.*
  static_files: index.html
  upload: index.html
